language: java

script: ./gradlew build jacocoTestReport --stacktrace

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - cd ./sources
  - chmod +x gradlew
  - ./gradlew wrapper
